### ISSUE TITLE
How can I use a project without a server?

### ISSUE THREAD

**Issue by Folleah** [NTumbleBit/NTumbleBit#103]
I would like to see the documentation on the requests to the server directly

**Comment by nopara73** [comment]
@Folleah Unfortunately we don't have this. Can I ask for what project would you need it?

**Comment by Folleah** [comment]
@nopara73 I meant using the API NTumbleBit.ClassicTumbler.Server.CLI without running client

**Comment by nopara73** [comment]
I know what you meant. We don't have documentation on that. It's because the API is not final yet.  

Also I'd like to note you could take a look at [ZeroLink](https://github.com/nopara73/ZeroLink/). It's the same Tumbler <-> clients architecture as TumbleBit, but when I designed it I designed it in mind that any wallet should be able to easily integrate it, so it's much simpler.  
I'm in the middle of developing it, the API endpoints can be found [here](https://github.com/nopara73/HiddenWallet/blob/zerolink/HiddenWallet.Documentation/TumblerApiSpecs.md).

**Comment by Folleah** [comment]
@nopara73 thank you!

**Comment by NicolasDorier** [comment]
@Folleah NTumbleBit is not using HTTP but pure TCP over TOR. What do you mean by "I would like to see the documentation on the requests to the server directly"?

**Comment by nopara73** [comment]
@NicolasDorier He wants to know what he has to implement in order to participate in a TumbleBit round.
